apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tingo.fullname" . }}
  labels:
    {{- include "tingo.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "tingo.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "tingo.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretName }}
                  key: datasource-url
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretName }}
                  key: datasource-username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretName }}
                  key: datasource-password
            - name: TINGO_REGISTER_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretName }}
                  key: register-secret
            - name: TINGO_GUEST_CODE
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretName }}
                  key: guest-code
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /info
              port: 8081
            timeoutSeconds: 2
            failureThreshold: 4
            initialDelaySeconds: 240
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /health
              port: 8081
            timeoutSeconds: 2
            failureThreshold: 4
            initialDelaySeconds: 120
            periodSeconds: 30
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /application.yml
              subPath: application.yml
            - name: temp
              mountPath: /tmp
      volumes:
        - name: config
          configMap:
            name: {{ include "tingo.fullname" . }}
        - name: temp
          emptyDir: {}
