# Spring property source for the Tingo application, providing default configuration
# Note that properties are considered in this order:
# http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-external-config

spring:
  profiles:
    active:
     - dev

  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    hikari:
      minimum-idle: 0
      maximum-pool-size: 10
    testOnBorrow: true
    validationQuery: SELECT 1
  flyway:
    # migrate if we don't have a baseline defined, i.e. Flyway has never run on that database.
    #baseline-on-migrate: true
    encoding: UTF-8
    #baseline-version: 0

management:
  endpoints:
    enabled-by-default: false
  endpoint:
    health:
      enabled: true
  server:
    port: 8081
